filenames = ["/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run289_20221030_125331.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run290_20221030_133453.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run291_20221030_141320.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run292_20221030_145414.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run295_20221030_162239.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run296_20221030_165208.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/100GeV/ECAL_Run297_20221030_180121.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run219_20221027_201930.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run220_20221027_212942.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run221_20221027_215547.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run222_20221027_224228.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run223_20221027_234459.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run224_20221028_005511.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run236_20221028_181028.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run237_20221028_181543.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run238_20221028_182101.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run239_20221028_182625.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run240_20221028_183127.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run241_20221028_183632.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run242_20221028_184102.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run243_20221028_184356.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run244_20221028_191458.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run245_20221028_204822.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run299_20221030_193002.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run306_20221031_030420.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/10GeV/ECAL_Run307_20221031_045514.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run225_20221028_020213.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run226_20221028_030024.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run300_20221030_200624.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run301_20221030_201900.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run302_20221030_211104.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run303_20221030_214229.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run304_20221030_222253.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/20GeV/ECAL_Run305_20221031_005707.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run227_20221028_040520.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run228_20221028_045451.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run308_20221031_064229.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run309_20221031_064841.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run310_20221031_072717.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run311_20221031_090051.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run314_20221031_142231.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/30GeV/ECAL_Run315_20221031_160420.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run230_20221028_120745.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run231_20221028_142553.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run232_20221028_151400.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run233_20221028_155608.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run235_20221028_164109.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run246_20221028_221022.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run247_20221028_231342.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/40GeV/ECAL_Run249_20221029_011935.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/50GeV/ECAL_Run250_20221029_062916.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/e+/50GeV/ECAL_Run251_20221029_074820.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run316_20221031_174112.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run317_20221031_181743.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run318_20221031_185850.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run319_20221031_193546.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run320_20221101_180104.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run321_20221101_183509.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run322_20221101_190441.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run323_20221101_191822.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run324_20221101_194053.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run325_20221101_200704.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run326_20221101_210820.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run327_20221101_221838.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run328_20221102_003104.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run329_20221102_011719.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run330_20221102_014933.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run331_20221102_024039.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run332_20221102_031856.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run333_20221102_035813.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run334_20221102_043109.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run335_20221102_050725.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run336_20221102_054310.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run337_20221102_061337.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run338_20221102_065030.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run339_20221102_071901.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run340_20221102_073415.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/mu+/108GeV/ECAL_Run341_20221102_074514.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/100GeV/ECAL_Run278_20221030_052756.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/100GeV/ECAL_Run279_20221030_055811.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/100GeV/ECAL_Run280_20221030_062824.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/100GeV/ECAL_Run281_20221030_065949.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/10GeV/ECAL_Run252_20221029_094052.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/10GeV/ECAL_Run253_20221029_103718.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run282_20221030_083736.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run283_20221030_090530.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run284_20221030_100522.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run285_20221030_103803.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run286_20221030_110840.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run287_20221030_114010.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/120GeV/ECAL_Run288_20221030_121336.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/20GeV/ECAL_Run254_20221029_110130.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/20GeV/ECAL_Run255_20221029_121851.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/20GeV/ECAL_Run256_20221029_132829.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/30GeV/ECAL_Run257_20221029_143424.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/30GeV/ECAL_Run258_20221029_153926.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/30GeV/ECAL_Run259_20221029_164844.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/30GeV/ECAL_Run312_20221031_105706.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/30GeV/ECAL_Run313_20221031_134407.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/40GeV/ECAL_Run260_20221029_172140.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/40GeV/ECAL_Run261_20221029_181215.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/40GeV/ECAL_Run262_20221029_191431.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/40GeV/ECAL_Run263_20221029_202127.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/50GeV/ECAL_Run264_20221029_210558.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/50GeV/ECAL_Run265_20221029_215346.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/50GeV/ECAL_Run266_20221029_224722.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/60GeV/ECAL_Run267_20221030_002012.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/60GeV/ECAL_Run268_20221030_005645.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/60GeV/ECAL_Run269_20221030_012041.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/60GeV/ECAL_Run270_20221030_014958.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/60GeV/ECAL_Run271_20221030_011553.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/80GeV/ECAL_Run272_20221030_021537.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/80GeV/ECAL_Run273_20221030_024202.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/80GeV/ECAL_Run274_20221030_031537.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/80GeV/ECAL_Run275_20221030_034149.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/80GeV/ECAL_Run276_20221030_041623.dat",
  "/cefs/higgs/wangjx/BeamData/ECAL/Particle/Combined/pi+/80GeV/ECAL_Run277_20221030_044414.dat"]
